name: WFC Server Build & Deploy

on:
  workflow_dispatch:
    inputs:
      release_tag:
        description: 'Release tag (e.g. v1.2.3)'
        required: true
        default: 'v0.0.1'       

env:
  REGISTRY: ghcr.io
  IMAGE_WFC_SERVER: ./pkmn-server
  API_URL: /api

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write   

    steps:
      # Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      # Log in to GitHub Container Registry
      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Copy example.env to .env and load
      - name: Copy example.env to .env
        run: cp example.env .env

      - name: Load .env file
        run: |
          set -a
          source .env
          set +a
      - name: Check entrypoint.sh presence
        run: cat ./pkmn-server/entrypoint.sh
      # Build and push wfc-server image
      - name: Build and push wfc-server
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ${{ env.IMAGE_WFC_SERVER }}/Dockerfile
          push: true
          build-args: |
            MARIADB_CONTAINER_NAME=${{ env.MARIADB_CONTAINER_NAME }}
            MARIADB_HOST=${{ env.MARIADB_HOST }}
            MARIADB_ROOT_PASSWORD=${{ env.MARIADB_ROOT_PASSWORD }}
            MARIADB_VERSION=${{ env.MARIADB_VERSION }}
            COWFC_DB_NAME=${{ env.COWFC_DB_NAME }}
            COWFC_DB_USER=${{ env.COWFC_DB_USER }}
            COWFC_DB_PASSWORD=${{ env.COWFC_DB_PASSWORD }}
            GTS_DB_NAME=${{ env.GTS_DB_NAME }}
            GTS_DB_USER=${{ env.GTS_DB_USER }}
            GTS_DB_PASSWORD=${{ env.GTS_DB_PASSWORD }}
            ADMIN_USERNAME=${{ env.ADMIN_USERNAME }}
            ADMIN_PASSWORD=${{ env.ADMIN_PASSWORD }}
            NETWORK_NAME=${{ env.NETWORK_NAME }}
          tags: |
            ${{ env.REGISTRY }}/${{ github.repository }}:latest
            ${{ env.REGISTRY }}/${{ github.repository }}:${{ github.sha }}
            ${{ env.REGISTRY }}/${{ github.repository }}:${{ github.ref_name }}
